<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" >
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
       <link href="/js/ligerUI/skins/Aqua/css/ligerui-all.css" rel="stylesheet" type="text/css" />
		<script src="/js/jquery.min.js" type="text/javascript"></script>   
		<script src="/js/ligerUI/js/core/base.js" type="text/javascript"></script>
		<script src="/js/ligerUI/js/plugins/ligerLayout.js" type="text/javascript"></script>
		<script src="/js/ligerUI/js/plugins/ligerTab.js" type="text/javascript"></script>
        <script src="/js/ligerUI/js/plugins/ligerDateEditor.js" type="text/javascript"></script> 

    	<script type="text/javascript">
    	    $(function () {
    	        $("#layout1").ligerLayout({ rightWidth: 240, height: '100%', isRightCollapse:false });
    	    });
/*
    	    function changeRegion(value)
    		{
    			switch(value)
    			{
    				case 'sumbyservice': 	document.getElementById('selectSumbyservice').style.display="none";    									
    									break;
    				case 'showonebyone':	 document.getElementById('selectShowonebyone').style.display="block";
    									break;
    				default:		 document.getElementById('selectSumbyservice').style.display="none";    									
    									break;
    			}
    		}
*/			
        </script>    
</head>
<body style="padding:0px;">   
  <div id="layout1" style="width:99.2%; margin:0 auto; margin-top:4px;"> 
        <div position="center" id="designPanel"> 
        <iframe id="contentiframe" name="content" frameborder=0  src="/showitem/showdesignmoney" width="100%" height="100%" scrolling="no"></iframe> 
        </div>        
           
 <div position="right" title="条件选择"style="margin:3px;" >  
 
 <div id="gap_top" style=" height:5px;">&nbsp;
 </div>
 <div id="gap_left" style="width:5px; height:100%; float:left;">&nbsp;
 </div>
 <div id="con" style="float:left;margin-left:10px; margin-top:10px">
<form id="condiction" name="condiction" method="post" target="content" action="/showitem/showdesignmoney" >
				
		<div>	
		<span>
		统计类型：	
		</span>
		<span> 		
	  	<select name="statisticsType" id="statisticsType" >
		<option value="sumbyservice" selected>按总和统计</option>
		<option value="showonebyone">按笔统计</option>
 		</select>
		</span>
		</div>
		
		<br>
		
<!-- 	
	<div id="selectSumbyservice" style="display:none;">	
	<span>
	
  	选择年：	
	</span>
	<span> 	  
	 <select name="sumbyservice" id="sumbyservice" >   
  	 <option value="all"selected="selected">所有</option>
  		< ?php
  			//循环输出数据显示
			foreach ($this->sumbyservice as $value)
			{
			
		?>
		<option value='< ?php echo $value['sumbyservice'];?>'>< ?php echo $value['sumbyservice'];?></option>
		< ?php
			}
		?> 
	 </select>
	 </span>
	</div>
	
	-->
	<br>
	<br>
	<table width="100%">
	<tr>
	<td width="50%" align="center"><input type="submit" name="Submit" value="  刷 新  "></td>
	<td width="50%" align="center"><input type="reset" name="Reset" value="  重 置  "></td>
	</tr>
	</table>
	
</form>

</div>

 </div> 
         
</div> 
</body>
</html>
