<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" >
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
       <link href="/js/ligerUI/skins/Aqua/css/ligerui-all.css" rel="stylesheet" type="text/css" />
		<script src="/js/jquery.min.js" type="text/javascript"></script>   
		<script src="/js/ligerUI/js/core/base.js" type="text/javascript"></script>
		<script src="/js/ligerUI/js/plugins/ligerLayout.js" type="text/javascript"></script>
		<script src="/js/ligerUI/js/plugins/ligerTab.js" type="text/javascript"></script>
        <script src="/js/ligerUI/js/plugins/ligerDateEditor.js" type="text/javascript"></script> 

    	<script type="text/javascript">
    	    $(function () {
    	        $("#layout1").ligerLayout({ rightWidth: 240, height: '100%', isRightCollapse:false });
    	    });
			
        </script>    
</head>
<body style="padding:0px;">   
  <div id="layout1" style="width:99.2%; margin:0 auto; margin-top:4px;"> 
        <div position="center" id="designPanel"> 
        <iframe id="contentiframe" name="content" frameborder=0  src="/statistics/graph" width="100%" height="100%" scrolling="no"></iframe> 
        </div>        
           
 <div position="right" title="条件选择"style="margin:3px;" >  
 
 <div id="gap_top" style=" height:5px;">&nbsp;
 </div>
 <div id="gap_left" style="width:5px; height:100%; float:left;">&nbsp;
 </div>
 <div id="con" style="float:left;margin-left:10px; margin-top:10px">
<form id="condiction" name="condiction" method="post" target="content" action="/statistics/graph" >
	<div>	
	<span>
  	选择年：	
	</span>
	<span> 	  
	 <select name="year" id="year" >
  		<?php
  			//循环输出数据显示
			foreach ($this->year as $value)
			{
			
		?>
		<option value='<?php echo $value['year'];?>'><?php echo $value['year'];?></option>
		<?php
			}
		?> 
	 </select>
	 </span>
	</div>
	
	
	<br>
	<br>
	<table width="100%">
	<tr>
	<td width="50%" align="center"><input type="submit" name="Submit" value="  刷 新  "></td>
	<td width="50%" align="center"><input type="reset" name="Reset" value="  重 置  "></td>
	</tr>
	</table>
	
</form>

</div>

 </div> 
         
</div> 
</body>
</html>
