<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />		
		<title>统计图表</title>	
		
		<script type="text/javascript" src="/js/jquery.min.js"></script>
		<script type="text/javascript">


$(function() {
	$('#container_pie').highcharts({
        chart: {           
			type: 'pie' //默认图表类型为饼状			
        },
        title: {
            text: '二所<?php echo $this->item[0]; ?>年开支结构图'  //图表标题
        },
		
        tooltip: {
            formatter: function() { //鼠标滑向图像提示框的格式化提示信息
                return '<b>' + this.point.name + '</b>: ' + twoDecimal(this.y)+' 元';
            }
        },
		
		legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'top',
                //x: -20,
                y: 100,
                borderWidth: 0
            },
		
        plotOptions: {
            pie: {
                allowPointSelect: true, //允许选中，点击选中的扇形区可以分离出来显示
                cursor: 'pointer',  //当鼠标指向扇形区时变为手型（可点击）
				showInLegend: true,  //如果要显示图例，可将该项设置为true
                dataLabels: {
                    enabled: true,  //设置数据标签可见，即显示每个扇形区对应的数据
                    color: '#000000',  //数据显示颜色
                    connectorColor: '#999',  //设置数据域扇形区的连接线的颜色
					style:{
						fontSize: '10px'  //数据显示的大小
					},
					
					 formatter: function() { //格式化数据
                        return  twoDecimal(this.percentage) + ' %';					    
                    }
                }
            }
        },
        series: [{ //数据列
            name: '用量',
			data: [
			       {name:'成本',y:<?php echo $this->item[1];?>,sliced:true,selected:true},
			       ['福利',<?php echo $this->item[2];?>],
			       ['发展基金',<?php echo $this->item[3];?>],
			       ['餐费',<?php echo $this->item[4];?>],
			       ['教育培训费',<?php echo $this->item[5];?>]

					]
        }]
    });
});



$(function () {
	$('#container_line').highcharts({
		chart: {
			type: 'area',                
			zoomType:'x'
		},
		title: {
			text: '二所<?php echo $this->item[0]; ?>年各开支情况'
		},
		
		xAxis: {
			categories: ['成本','福利','发展基金','餐费','教育培训费'	]
			
		},
		yAxis: {
			title: {
				text: '(元)'
			}		
		},
		tooltip: {
			valueSuffix: '元',
			shared: false,
			useHTML: true
		},
		
		 plotOptions: {
                area: {
                    fillColor: {
                        linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                        stops: [
                            [0, Highcharts.getOptions().colors[0]],
                            [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                        ]
                    },
                    lineWidth: 1,
                    marker: {
                        enabled: false
                    },
                    shadow: false,
                    states: {
                        hover: {
                            lineWidth: 1
                        }
                    },
                    threshold: null,
                    dataLabels: {
                        enabled: true                       
						}
                }
            },
		
		series: [
		         {
			name: '<?php echo $this->item[0]; ?>年使用量',	
                data:[
		                <?php 
		                echo $this->item[1].",";
		                echo $this->item[2].",";
		                echo $this->item[3].",";
		                echo $this->item[4].",";
		                echo $this->item[5];
		                ?>
                ]
		       }  	         			
		 ]
	});
});


		
$(function () {
        $('#container_column').highcharts({
            chart: {
                type: 'column',
				zoomType:'x'
            },
            title: {
                text: '二所<?php echo $this->item[0]; ?>年各开支情况'
            },			
            xAxis: {
                categories: ['成本','福利','发展基金','餐费','教育培训费'	]				
            },
            yAxis: {
                min: 0,
                title: {
                    text: '（元）'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                    '<td style="padding:0"><b>{point.y:.1f} 元</b></td></tr>',
                footerFormat: '</table>',
                shared: false,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0,                   
                    dataLabels: {
                        enabled: true                       
						}
                    
                }
            },
            series: [
			{
                name: '<?php echo $this->item[0]; ?>年使用量',	
                data:[
		                <?php 
		                echo $this->item[1].",";
		                echo $this->item[2].",";
		                echo $this->item[3].",";
		                echo $this->item[4].",";
		                echo $this->item[5];
		                ?>
                ]			
            }			
			]
        });
    });	


//保留2位小数
function twoDecimal(x) {
    var f_x = parseFloat(x);
    if (isNaN(f_x)) {
        //alert('错误的参数');
        return false;
    }
    var f_x = Math.round(x * 100) / 100;
    var s_x = f_x.toString();
    var pos_decimal = s_x.indexOf('.');
    if (pos_decimal < 0) {
        pos_decimal = s_x.length;
        s_x += '.';
    }
    while (s_x.length <= pos_decimal + 2) {
        s_x += '0';
    }
    return s_x;
}
    </script>
	</head>
	<body >
	
<script src="/js/highcharts/highcharts.js"></script>
<script src="/js/highcharts/modules/exporting.src2.js"></script>
<script src="/js/highcharts/themes/wosshzhb_border.js"></script>




<div id="main" style="width:99.2%; height:100%; margin:0 auto; "> 
	<div id="container_pie" style="width:50%; height: 300px;float:left;"></div>
	<div id="container_line" style="width:50%; height: 300px;float:left;"></div>
	<div id="container_column" style="width:100%;height: 300px;float:left;"></div>
</div>

	</body>
</html>
