<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>业务号统计情况</title>

<link rel="stylesheet" type="text/css" href="/js/ligerUI/skins/Aqua/css/ligerui-all.css"/>
<!--  <script type="text/javascript" src="/js/jquery.min.js"></script> -->
<script type="text/javascript" src="/js/jquery2_1_0.js"></script>
<script type="text/javascript" src="/js/ligerUI/js/core/base.js"></script>
<script type="text/javascript" src="/js/ligerUI/js/plugins/ligerGrid.js"></script>

<link href="/js/ligerUI/skins/ligerui-icons.css" rel="stylesheet" type="text/css" />
<script src="/js/ligerUI/js/plugins/ligerToolBar.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerDialog.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerFilter.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerDrag.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerResizable.js" type="text/javascript"></script>
<script src="/js/ligerUI/ligerGrid.showFilter.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerTab.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerTextBox.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerCheckBox.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerComboBox.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerDateEditor.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerSpinner.js" type="text/javascript"></script>
<script type="text/javascript">

    //去掉  大于小于包括,并改变顺序
    $.ligerDefaults.Filter.operators['string'] =
    $.ligerDefaults.Filter.operators['text'] =
    ["like" , "equal", "notequal", "startwith", "endwith" ];
var navtab = null;
        $(function ()
        {
            $("#tab").ligerTab();
            navtab = $("#tab").ligerGetTabManager();
        });
        
        
        
 $(function()
 {
 	var jsonObj = {};
	jsonObj.Rows =
	<?php echo $this->item; ?>; 
	
	var columns =
            [				
                { display: '报账时间', name: 'date', type:'date'},
                { display: '业务号', name: 'serviceId' ,type:'text'},
				{ display: '制作费（单位：元）', name: 'make',editor: {type:'float'}},
                { display: '差旅费（单位：元）', name: 'travel',editor: {type:'float'}},
                { display: '餐费（单位：元）', name: 'meals',editor: {type:'float'}}
                    
             ];
			 
 	window['g']=$("#maingrid").ligerGrid({
	  columns:columns,
	  data:jsonObj,
	  //title:'财务报账',
	  showTitle:false,
	  width:'99%',
	  height:'460px',
	  //height:'80%',
	  pageSize:10,
	  pageSizeOptions:[10,20,30,40],
	  toolbar: { items: [{ text: '导出excel', click: itemsave, icon: 'save'}] },

      onSelectRow: function (rowdata, rowindex)
      {
         $("#txtrowindex").val(rowindex);
      },
	 enabledEdit: false, clickToEdit: false, isScroll: true      
	 //onBeforeSubmitEdit: f_onBeforeSubmitEdit	 
	
	});
	 	
	function itemsave()
        {
           window.open("/statistics/sidexportexcel");
        }	
		
	
 });
 
	
</script>

</head>

<body >
<!--  <div id="tab" style="width: 100%;height:100%;overflow:hidden; border:0px;"> -->

<div title="财务报账情况表" id="maingrid" style="margin:0 auto;" ></div>

	
<!--  </div> -->

</body>
</html>
