<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/js/ligerUI/skins/Aqua/css/ligerui-all.css"/>
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/ligerUI/js/core/base.js"></script>
<script type="text/javascript" src="/js/ligerUI/js/plugins/ligerGrid.js"></script>

<link href="/js/ligerUI/skins/ligerui-icons.css" rel="stylesheet" type="text/css" />
<script src="/js/ligerUI/js/plugins/ligerToolBar.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerDialog.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerFilter.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerDrag.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerResizable.js" type="text/javascript"></script>
<script src="/js/ligerUI/ligerGrid.showFilter.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerTab.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerTextBox.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerCheckBox.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerComboBox.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerDateEditor.js" type="text/javascript"></script>
<script src="/js/ligerUI/js/plugins/ligerSpinner.js" type="text/javascript"></script>
<script type="text/javascript">

    //去掉  大于小于包括,并改变顺序
    $.ligerDefaults.Filter.operators['string'] =
    $.ligerDefaults.Filter.operators['text'] =
    ["like" , "equal", "notequal", "startwith", "endwith" ];
var navtab = null;
        $(function ()
        {
            $("#tab").ligerTab();
            navtab = $("#tab").ligerGetTabManager();
        });
var userData = [{ userRight: 99, text: '超级用户' }, { userRight: 2, text: '只读用户'}, { userRight: 1, text: '普通用户'}];
 $(function()
 {
 	var jsonObj = {};
	jsonObj.Rows =
	<?php echo $this->item; ?>; 
	
	var columns =
            [
				/*{ display: '序号', name: 'id',type:'int'},*/
                { display: '用户', name: 'user', type:'text'},
                
				{ display: '权限', name:'userRight' ,type:'int',
    				editor:{type:'select',data:userData,valueField:'userRight'},
    				render:function(item)
    				{
        				if(parseInt(item.userRight) == 99)
                			return '超级用户';
        				else if(parseInt(item.userRight) == 2)
            				return '只读用户';
        				else 
            				return '普通用户';
        			}
  
    			}
				<?php 	  		
		  				if (99 == $this->userRight) 
						{
							require_once APPLICATION_PATH.'/models/AlterUser.php';
						}
							
                ?>			
             ];
			 
 	window['g']=$("#maingrid").ligerGrid({
	  columns:columns,
	  data:jsonObj,
	  showTitle:false,
	  width:'99%',
	  height:'460px',
	  pageSize:10,
	  pageSizeOptions:[10,15,20,30],
	  toolbar: { items: [{ text: '高级自定义查询', click: itemclick, icon: 'search2'},
	                     { text: '添加用户', click: itemaddmember, icon: 'add'},
	  			{ text: '刷新', click: itemrefresh, icon: 'load'}]
               },

      onSelectRow: function (rowdata, rowindex)
      {
         $("#txtrowindex").val(rowindex);
      },
	 enabledEdit: true, clickToEdit: false, isScroll: false         
	 
	
	});
   function itemclick()
        {
            g.options.data = jsonObj;
            g.showFilter();
        }

	 
	function itemrefresh()
    {
		window.location = "/admin/index";
    }			

	function itemaddmember()
	{   
		
		<?php 
		/*	  		
  			if (99 == $this->userRight) 
			{
				$this->render("addmember");
			}
			*/
			//echo "nimei";
			//exit();
				
        ?>	
        
		window.location = "/admin/addmember";
	
		//alert("对不起，您没有该权限");
	}
 });
	<?php 
		if (99 == $this->userRight) 
		{
			require_once APPLICATION_PATH.'/models/modifyUserRightFunction.php';
		}
    ?>
</script>

</head>

<body >
<div id="tab" style="width: 100%;height:100%;overflow:hidden; border:0px;">

<div title="用户管理" id="maingrid" style="margin:0 auto;" ></div>

	
</div>

</body>
</html>



