<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>
</title>
    <link href="/js/ligerUI/skins/Aqua/css/ligerui-all.css" rel="stylesheet" type="text/css" /> 
    <link href="/js/ligerUI/skins/Gray/css/all.css" rel="stylesheet" type="text/css" /> 
    <script src="/js/jquery.min.js" type="text/javascript"></script>
    <script src="/js/ligerUI/js/core/base.js" type="text/javascript"></script>
    <script src="/js/ligerUI/js/plugins/ligerForm.js" type="text/javascript"></script>
    <script src="/js/ligerUI/js/plugins/ligerDateEditor.js" type="text/javascript"></script>
    <!--  
    <script src="/js/ligerUI/js/plugins/ligerComboBox.js" type="text/javascript"></script>
    <script src="/js/ligerUI/js/plugins/ligerCheckBox.js" type="text/javascript"></script>
    <script src="/js/ligerUI/js/plugins/ligerDialog.js" type="text/javascript"></script>
    <script src="/js/ligerUI/js/plugins/ligerRadio.js" type="text/javascript"></script>
    <script src="/js/ligerUI/js/plugins/ligerSpinner.js" type="text/javascript"></script>
    -->
    <script src="/js/ligerUI/js/plugins/ligerButton.js" type="text/javascript"></script>   
    <script src="/js/ligerUI/js/plugins/ligerTextBox.js" type="text/javascript"></script> 
    <script src="/js/ligerUI/js/plugins/ligerTip.js" type="text/javascript"></script>
      <script src="/js/jquery-validation/jquery.validate.min.js" type="text/javascript"></script> 
    <script src="/js/jquery-validation/jquery.metadata.js" type="text/javascript"></script>
    <script src="/js/jquery-validation/messages_cn.js" type="text/javascript"></script>
     <script type="text/javascript">
        var eee;
        $(function ()
        {
            $.metadata.setType("attr", "validate");
            var v = $("form").validate({
                //debug: true,
                errorPlacement: function (lable, element)
                {
                    if (element.hasClass("l-textarea"))
                    {
                        element.ligerTip({ content: lable.html(), target: element[0] }); 
                    }
                    else if (element.hasClass("l-text-field"))
                    {
                        element.parent().ligerTip({ content: lable.html(), target: element[0] });
                    }
                    else
                    {
                        lable.appendTo(element.parents("td:first").next("td"));
                    }
                },
                success: function (lable)
                {
                    lable.ligerHideTip();
                    lable.remove();
                },
                submitHandler: function ()
                {
                    $("form .l-text,.l-textarea").ligerHideTip();
                    //alert("Submitted!")
                    form1.submit();
                }
            });
            $("form").ligerForm();            
        });  
    </script>
     
 <style type="text/css">
           body{ font-size:12px;}
        .l-table-edit {}
        .l-table-edit-td{ padding:2px;}
        .l-button-submit,.l-button-test{width:80px; float:left; margin-left:100px; padding-bottom:2px;}
        .l-verify-tip{ left:230px; top:120px;}
    </style>
     
     
</head>

<body style="padding:10px">

    <form name="form1" method="post"  id="form1" action="/admin/acceptpassword">
        <table cellpadding="0" cellspacing="0" class="l-table-edit">
            
            <tr>
                <td align="right" class="l-table-edit-td">新密码:</td>
                <td align="left" style="width:160px" class="l-table-edit-td"><input name="newPwd" type="password" id="newPwd" validate="{required:true,minlength:5}"/></td>
                <td align="left"></td>
            </tr>          
            
          	<tr>
               <td align="right" class="l-table-edit-td">确认密码:</td>
               <td align="left" style="width:160px" class="l-table-edit-td"><input name="conPwd" type="password" id="conPwd" validate="{equalTo:'#newPwd'}"/></td>
               <td align="left"></td>
            </tr>      
          
          
        </table>
 <br />
		<input type="submit" value="提交" id="Button1" class="l-button l-button-submit" /> 
    </form>
   
    
</body>
</html>